default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 3306
  username: root
  password: Password
  host: localhost
  socket: /tmp/mysql.sock
development:
  <<: *default
  database: nginx_puma_development
test:
  <<: *default
  database: nginx_puma_test
staging:
  <<: *default
  host: 
  username: 
  password: 
  database: nginx_puma_staging
production:
  <<: *default
  host: 
  username: 
  password: 
  database: nginx_puma_production